package src;

import com.sun.rowset.JdbcRowSetImpl;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.sql.RowSet;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alan.Ryan
 */
public class TestDB extends javax.swing.JFrame {

    /**
     * Creates new form TestDB
     */
    public TestDB() {
        initComponents();

        try {

            rowSet.setUrl("jdbc:mysql://itshares.student.litdom.lit.ie:3306/iseq3");
            rowSet.setUsername("sd4user");
            rowSet.setPassword("pass");
            rowSet.setCommand("SELECT * FROM prices limit 5");
            rowSet.execute();
            String results = "";

            ResultSetMetaData metaData = rowSet.getMetaData();

            int numberOfColumns = metaData.getColumnCount();

            String temp;
            for (int i = 0; i < numberOfColumns - 1; i++) {
                temp = String.format("%-18s|", colNnames[i]);
                results += temp;
            }
            results += "\n";

            while (rowSet.next()) {

                for (int i = 1; i < numberOfColumns; i++) {
                    //String temp = String.format("%-20s= %s" ,resultSet.getObject(i) );
                    temp = String.format("%-18s|", rowSet.getObject(i));

                    results += temp;
                }//end for
                results += "\n";
            }

            output.setText(results);

        }//end try
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        alphaButton = new javax.swing.JButton();
        priceIncrButton = new javax.swing.JButton();
        spButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Control Panel"));

        alphaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphaButton.setText("Display Companys Alphabetical Order");
        alphaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaButtonActionPerformed(evt);
            }
        });
        controlPanel.add(alphaButton);

        priceIncrButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceIncrButton.setText("Display Companys By Price Increase");
        priceIncrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceIncrButtonActionPerformed(evt);
            }
        });
        controlPanel.add(priceIncrButton);

        spButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spButton.setText("Call Stored Procedure");
        spButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spButtonActionPerformed(evt);
            }
        });
        controlPanel.add(spButton);

        batchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batchButton.setText("Call Batch Statements");
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        controlPanel.add(batchButton);

        getContentPane().add(controlPanel, java.awt.BorderLayout.NORTH);

        outputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        outputPanel.setLayout(new java.awt.BorderLayout());

        output.setColumns(20);
        output.setEditable(false);
        output.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        outputPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(outputPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spButtonActionPerformed
        //btn3
        //output.setText("");
        try {
            rowSet.setCommand("SELECT * FROM prices limit 5");
            rowSet.execute();

        } catch (SQLException ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(null, ex.toString());

        }
        //updateOutput("select * from prices");
    }//GEN-LAST:event_spButtonActionPerformed

    private void alphaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaButtonActionPerformed
//btn1        
        updateOutput("SELECT * FROM prices limit 11");
    }//GEN-LAST:event_alphaButtonActionPerformed

    private void priceIncrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceIncrButtonActionPerformed
        //btn2
        //updateOutput("");

    }//GEN-LAST:event_priceIncrButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        //btn4
        //updateOutput("");
    }//GEN-LAST:event_batchButtonActionPerformed

    private void updateOutput(String query) {
        output.setText("");
        try {
            System.out.println(query);
            rowSet.setCommand(query);
            rowSet.execute();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestDB().setVisible(true);
            }
        });
    }

    private JdbcRowSetImpl rowSet = new JdbcRowSetImpl();
    private String colNnames[] = new String[]{"company ID", "Company Name", "Curr Price", "Price Yest", "Trd Yest", "Yr Low", "Year High", "Year listed"};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alphaButton;
    private javax.swing.JButton batchButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JButton priceIncrButton;
    private javax.swing.JButton spButton;
    // End of variables declaration//GEN-END:variables
}
